// lib/ingredients.ts
import {
  Ingredient,
  IngredientDomain,
  IngredientEffectTag,
  IngredientId,
} from "./types";

export const INGREDIENTS: Record<IngredientId, Ingredient> = {
  MANDRAKE_ROOT: {
    id: "MANDRAKE_ROOT",
    name: "Mandrake Root",
    icon: "🌿",
    domain: "PROTECTION",
    effectTags: ["SOFT_PROTECT"],
    corruptionValue: -0.15,
    shortDescription: "A root of life that calms volatile magic.",
    flavorLines: [
      "A root of life—its cry still echoes.",
      "Green veins coil; the cauldron cools a breath.",
    ],
  },
  TEARS_OF_THE_MOON: {
    id: "TEARS_OF_THE_MOON",
    name: "Tears of the Moon",
    icon: "💧",
    domain: "PROTECTION",
    effectTags: ["SOFT_PROTECT", "MARK_RITUAL"],
    corruptionValue: -0.1,
    shortDescription: "Silver drops that wash away traces of the Hollow.",
    flavorLines: [
      "Silver drops purify the cauldron's edge.",
      "Moonlight condenses into mercy.",
    ],
  },
  EYE_OF_NEWT: {
    id: "EYE_OF_NEWT",
    name: "Eye of Newt",
    icon: "🧅",
    domain: "DIVINATION",
    effectTags: ["ALIGNMENT_REVEAL"],
    corruptionValue: 0.05,
    shortDescription: "A restless eye that glimpses hidden loyalties.",
    flavorLines: [
      "The eye opens—seeing truths not meant for mortals.",
      "A lidless gaze turns upon the Circle.",
    ],
  },
  CANDLE_WAX: {
    id: "CANDLE_WAX",
    name: "Candle Wax",
    icon: "🕯️",
    domain: "AMPLIFICATION",
    effectTags: ["BOOST_CORRUPTION"],
    corruptionValue: 0.06,
    shortDescription: "Melted focus that sharpens whatever the ritual becomes.",
    flavorLines: [
      "Flame feeds flame; focus sharpens.",
      "A drip of tallow—power gathers.",
    ],
  },
  RAVEN_FEATHER: {
    id: "RAVEN_FEATHER",
    name: "Raven Feather",
    icon: "🪶",
    domain: "MISDIRECTION",
    effectTags: ["DISTORT_VISION", "NOISE_ONLY"],
    corruptionValue: 0.08,
    shortDescription: "A black quill that scatters truths into whispers.",
    flavorLines: [
      "A feather falls—secrets scatter like smoke.",
      "Black quill ripples; messages tangle.",
    ],
  },
  BONE_DUST: {
    id: "BONE_DUST",
    name: "Bone Dust",
    icon: "💀",
    domain: "DIVINATION",
    effectTags: ["ALIGNMENT_REVEAL", "DISTORT_VISION"],
    corruptionValue: 0.12,
    shortDescription: "Charred bone that lets the dead speak—unclearly.",
    flavorLines: [
      "Ash to ash—the dead whisper counsel.",
      "Char and calcium: the grave speaks.",
    ],
  },
  IRON_THORN: {
    id: "IRON_THORN",
    name: "Iron Thorn",
    icon: "🗡️",
    domain: "CORRUPTION",
    effectTags: ["BLOCK_PROTECTION"],
    corruptionValue: 0.14,
    shortDescription: "A cold barb that unthreads protective charms.",
    flavorLines: [
      "Iron bites green—wards grow quiet.",
      "A cold barb unthreads the charm.",
    ],
  },
  SHADOW_ASH: {
    id: "SHADOW_ASH",
    name: "Shadow Ash",
    icon: "🌫️",
    domain: "CORRUPTION",
    effectTags: ["BOOST_CORRUPTION"],
    corruptionValue: 0.18,
    shortDescription: "Soot of void that devours light from the ritual.",
    flavorLines: [
      "Cinders blacken—the night leans in.",
      "A soot of void devours the light.",
    ],
  },
  BLOOD_OF_THE_INNOCENT: {
    id: "BLOOD_OF_THE_INNOCENT",
    name: "Blood of the Innocent",
    icon: "🩸",
    domain: "CORRUPTION",
    effectTags: ["BOOST_CORRUPTION"],
    corruptionValue: 0.3,
    shortDescription: "Forbidden blood that fuels lethal backfires.",
    flavorLines: [
      "The blood sizzles—something ancient stirs.",
      "Red steam coils; hunger wakes.",
    ],
  },
  SILVER_THREAD: {
    id: "SILVER_THREAD",
    name: "Silver Thread",
    icon: "🧵",
    domain: "DIVINATION",
    effectTags: ["ALIGNMENT_REVEAL", "MARK_RITUAL"],
    corruptionValue: 0.04,
    shortDescription: "A shining filament that binds fates together.",
    flavorLines: [
      "A glinting thread stitches two fates.",
      "Moonlit fiber hums between distant hearts.",
    ],
  },
  CRYSTAL_BALL: {
    id: "CRYSTAL_BALL",
    name: "Crystal Ball",
    icon: "🔮",
    domain: "DIVINATION",
    effectTags: ["ALIGNMENT_REVEAL"],
    corruptionValue: 0.0,
    shortDescription: "Oracle-exclusive: When you select this, immediately glimpse what ingredient someone else chose.",
    flavorLines: [
      "The glass sphere shows what eyes cannot see.",
      "Crystal whispers secrets—truth unfiltered.",
    ],
  },
};

export const INGREDIENT_LIST = Object.values(INGREDIENTS);
